---
- hosts: 172.31.32.35
  become: yes
  tasks:
  - name: Install Java 1.8
    yum: name=java-1.8.0-openjdk-devel state=present

  - name: Download Tomcat
    get_url: url=https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz dest=/opt

  - name: Extract archive
    command: chdir=/opt tar xvf apache-tomcat-9.0.65.tar.gz

  - name: Change ownership of Tomcat installation
    file: path=/opt/apache-tomcat-9.0.65 owner=ansible group=ansible state=directory recurse=yes mode=0770

  - name: copy jar/war onto tomcat servers
    copy:
      src: /home/ansible/java-tomcat-maven-example.war
      dest: /opt/apache-tomcat-9.0.65/webapps

  - name: Start Tomcat
    command: "nohup /opt/apache-tomcat-9.0.65/bin/startup.sh"
